using UnityEngine;

/// <summary>
/// SceneBGMConfig 風書き方に統一した就活向け Singleton MonoBehaviour
/// - Instance アクセス時に自動生成
/// - DontDestroyOnLoad + 重複破棄を維持
/// - Scene に置いた場合は Inspector 設定反映
/// - 派生クラスで Awake 拡張可能
/// </summary>
public class SingletonMonoBehaviour<T> : MonoBehaviour where T : MonoBehaviour
{
    private static T _instance;

    /// <summary>
    /// Singleton インスタンス取得
    /// シーン上に存在しなければ自動生成
    /// </summary>
    public static T Instance
    {
        get
        {
            if (_instance == null)
            {
                // シーン上の既存オブジェクトを優先
                _instance = FindAnyObjectByType<T>();

                if (_instance == null)
                {
                    // 無ければ自動生成
                    GameObject go = new GameObject(typeof(T).Name);
                    _instance = go.AddComponent<T>();
                    Debug.Log($"[Singleton] {typeof(T).Name} was auto-created.");
                }
            }
            return _instance;
        }
    }

    #region Inspector 設定可能なオプション
    [Header("▼Singleton 設定")]
    [SerializeField, Tooltip("Scene 上に配置した場合のみ Inspector で設定可能")]
    private bool doNotDestroyOnLoad = true;

    [SerializeField, Tooltip("重複した場合に Destroy するか")]
    private bool shouldDestroyDuplicates = true;

    /// <summary>読み取り専用プロパティ</summary>
    internal bool DoNotDestroyOnLoad => doNotDestroyOnLoad;

    /// <summary>読み取り専用プロパティ</summary>
    internal bool ShouldDestroyDuplicates => shouldDestroyDuplicates;
    #endregion

    /// <summary>
    /// Awake で既存インスタンスとの重複チェック
    /// </summary>
    protected virtual void Awake()
    {
        if (_instance == null)
        {
            _instance = this as T;

            if (doNotDestroyOnLoad)
                DontDestroyOnLoad(gameObject);
        }
        else if (_instance != this)
        {
            if (shouldDestroyDuplicates)
            {
                Destroy(gameObject);
                Debug.LogWarning($"[Singleton] Duplicate {typeof(T).Name} destroyed.");
            }
            else
            {
                Debug.LogWarning($"[Singleton] Duplicate {typeof(T).Name} exists but not destroyed.");
            }
        }
    }

    #region Utility
    /// <summary>Instance が初期化済みか確認</summary>
    protected bool IsInstanceInitialized() => _instance != null;

    /// <summary>自動生成されたかどうかを判定</summary>
    protected bool IsAutoGenerated => _instance != null && _instance.gameObject.scene.name == null;
    #endregion
}
